#!/usr/bin/env bash
#Display information about subdomains
#shellcheck disable=SC2086

get_subdomain_info() {
	local domain="$1"
	local subdomain="$2"
	dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; printf "The subdomain %s is a %s record and points to %s\n", var, $4, $5}' var="$subdomain"
}
for subdomain in "www" "lb-01" "web-01" "web-02"
do
	if [ -z "$2" ] || [ "$2" == "$subdoamin" ] ;
	then
		get_subdomain_info "$1" "$subdomain"
	fi
done
