#!/usr/bin/env bash
#Display information about subdomains
#shellcheck disable=SC2086

get_subdomain_info() {
	local domain="$1"
	local subdomain="$2"
	local record_type

	if [ -z "$subdomain" ]; then
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
		result=$(dig +short "$sub.$domain")
		if [ -n "$result" ]; then
			record_type=$(dig +short "$sub.$domain") | awk 'NR==1 {print toupper($1)}'
			destination=$(dig +short "$sub.$domain" | awk 'NR==1 {print $1}')
			echo "The subdomain $sub is a $record_type record and points to $destination"
		else
			echo "The subdomain $sub does not exist for domain $domain"
		fi
	done
}
if [ "$#" -eq 0 ]; then
	echo "Usage: $0 domain [subdomain]"
	exit 1
elif [ "$#" -eq 1 ]; then
	domain="$1"
	get_subdomain_info "$domain"
elif [ "$#" -eq 2 ]; then
	domain="$1"
	subdomain="$2"
	get_subdomain_info "$domain" "$subdomain"
else
	echo "Usage: $0 domain [subdomain]"
fi
