#!/usr/bin/env bash
#install nginx and configure it
#Configure Nginx to listen on port 80
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" |sudo tee  /var/www/html/index.nginx-debian.html > /dev/null
service nginx restart
