#!/usr/bin/env bash
#install nginx and configure it
#Configure Nginx to listen on port 80
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/ngninx/sites-available/default
sudo service nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html
