#!/user/bin/env bash
#install nginx and configure it
#Configure Nginx to listen on port 80
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.nginx.html
service nginx restart
