#!/usr/bin/env bash
#install nginx and configure it
#Configure Nginx to listen on port 80
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo chwon -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

sed -i '37i\rewrite ^/redirect_me  https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
