#!/bin/env bash
# Create a custom error page
cat <<EOF > /usr/share/nginx/html/404.html
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF

# Configure nginx to use the custom error page for 404 errors
echo 'server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        error_page 404 /404.html;
        location = /404.html {
                internal;
        }

        location / {
                return 404;
        }
}' > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
