#!/usr/bin/env bash
#install nginx and configure it
#Configure a new Ubuntu server with a custom HTTP header response
sudo apt-get -y install nginx
sudo service nginx start
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
sudo service nginx restart
