#!/usr/bin/env bash
#install nginx and configure it
#Configure a new Ubuntu server with a custom HTTP header response
sudo apt-get -y install nginx
sudo service nginx start
sudo sed -i '/listen 80 default_server;/a add_header X-Served-By $hostname;' /etc/nginx/sites-available/default
# Step 2: Create a custom Nginx configuration file for the custom header
sudo tee /etc/nginx/conf.d/custom_header.conf << EOF
server {
    listen 80 default_server;
    server_name _;

    location / {
        add_header X-Served-By \$hostname;
        # Add your other server configurations here if needed
    }
}
EOF
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
