#!/usr/bin/env bash

# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Allow HTTP traffic
ufw allow 'Nginx HTTP'

# Create HTML directory and files
mkdir -p /var/www/html
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Configure Nginx
cat <<EOF > /etc/nginx/sites-available/default
server {
    root /var/www/html/;
    index index.html index.htm;
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By "\$HOSTNAME";

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
EOF

# Restart Nginx
service nginx restart

