#!/usr/bin/env bash
#A backup script
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql_password>"
    exit 1
fi

mysqldump -u root -p$1 --all-databases > backup.sql
tar -czvf $(date +%d-%b-%Y)".tar.gz" backup.sql
