#!/usr/bin/env bash
# change Localhost to 127.0.0.2
# the >/dev/null redirect the tee out but not to the output
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts >/dev/null
#Resolve facebook.com to 8.8.8.8
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf  >/dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts  >/dev/null
